ports:
  web:
    expose: true
    port: 80
  websecure:
    expose: true
    port: 443

ingressRoute:
  dashboard:
    enabled: true

additionalArguments:
  - "--providers.kubernetescrd"
  - "--providers.kubernetesingress"

persistence:
  enabled: true
  storageClass: local-nas
  size: 2Gi
